apiVersion: apps/v1
kind: Deployment

metadata:
  name: ml-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ml-api

  template:

    metadata:
      labels:
        app: ml-api

    spec:

      containers:

      - name: ml-api

        image: harpreetsi94/house-price-ml:1.0

        ports:
        - containerPort: 8000